# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: ${env.LOCATION}
  datasource:
    url:      ${env.SPRING_DATASOURCE_URL}
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}

my_email: ${env.EMAIL}
my_password: ${env.PASSWORD}
my_url: ${env.URL}
my_username: ${env.USERNAME}

